### ISSUE TITLE
The ReadMe does not spesify how this extension is to be used

### ISSUE THREAD

**Issue by Oliver2213** [mopidy/mopidy-soundcloud#54]
I'm fairly new to mopidy, so this could be my inability to understand how things work together... but i've installed the simple web interface, and tried the iOS MPD client "mPoD", and can't locate anything soundcloud related. not under playlists, songs, artists, albums, browse... etc.
I did see an issue where someone stated there needs to be more documentation on it's actual use, and I highly concur, especially as a new user to mopity. 
I got a token from http://www.mopity.com/authenticate, and entered it into my config file, so I don't think that's the problem.
If this is my lack of experience and / or this particular app's fault, I apologize, but as it stands now, there isn't really any specific (or broad, for that matter) instructions on this extension's use

**Comment by kingosticks** [comment]
Hi,
All Mopidy backend extensions work pretty much the same way and provide search results, browse entries and sometimes also playlists. mopidy-soundcloud doesn't provide any playlists but allows you to Browse things you've liked and followed etc. How exactly that's presented to you really depends on your choice of client. The Mopidy webclients are generally quite similar and you should see a SoundCloud entry in the Browse section. If you don't then you probably haven't got things setup quite right.  Have a good look at https://docs.mopidy.com/en/latest/debian/#differences-when-running-as-a-system-service if you have not already done so.  If you still have problems then please post at http://discuss.mopidy.com (include the output of `mopidy deps`) and have a look for any errors in your log files.

Any special extension instructions or config options are usually included in the extension's README page, just as they are in this case. If you think more documentation would be helpful then it would likely be relevant for all extensions and better suited in the core Mopidy project rather than mopidy-soundcloud specifically. Improvements to the documentation are very welcome.
