### ISSUE TITLE
SoundCloud API returns 429

### ISSUE THREAD

**Issue by amki** [mopidy/mopidy-soundcloud#89]
Apparently the client key for mopidy-soundcloud has breached 15000 calls in 24 hours so the soundcloud API returns 429.

Is there anything that can be easily done about this?

I guess when registering one client identifier per Installation (via SoundCloud's SDK) one would need to implement OAuth?

**Comment by kingosticks** [comment]
Will that require interaction from the user every time mopidy is run? Like the Spotify oauth flow does? We've previously avoided this due to the awkwardness this presents to headless installs. But it sounds like it's needed here too.

**Comment by kingosticks** [comment]
OK, so I was on about something else because I didn't bother to to read the source so we can ignore all my above comment.

On IRC, @adamcik has pointed out http://stackoverflow.com/questions/41631525/rate-limit-error-when-using-soundcloud-api so it *might* be a problem at their end. The 15k limit is only for play requests so if it's not a problem with soundcloud then we must have a problem with the extension. 

Registering a new client id might not work very well as their application form warns:
> Please allow up to two weeks to receive an update on the outcome of your application.

**Comment by kingosticks** [comment]
Registering a new client per user really is a dead-end, Soundcloud are absolutely useless at reviewing their applications, they clearly don't expect people to us their API this way. I vote we close this issue and wait to see if it happens again.

**Comment by hobbyquaker** [comment]
it seems that happened again: 
```javascript
{"errors":[{"meta":{"rate_limit":{"bucket":"by-client","max_nr_of_requests":15000,"time_window":"PT24H","name":"plays"},"remaining_requests":0,"reset_time":"2018/02/07 12:05:05 +0000"}}]}
```

**Comment by hobbyquaker** [comment]
and again today - that's sad... :(
